use_frameworks!
platform :ios, '11.0'

target 'PediAR' do
	pod 'SnapKit', '~> 4.0.0'
	pod 'lottie-ios'
	pod 'Kingfisher', '~> 4.0'
	pod 'Agrume', :git => 'https://github.com/JanGorman/Agrume.git'
	pod 'SwiftyJSON'
end
